// default package
// Generated 28 Dec, 2014 2:51:29 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderLines generated by hbm2java
 */
@Entity
@Table(name = "OrderLines", catalog = "salesorderapp")
public class OrderLines implements java.io.Serializable {

	private OrderLinesId id;
	private Product product;
	private SaleOrder saleOrder;
	private int orderQuantity;
	private BigDecimal unitPrice;
	private BigDecimal totalPrice;

	public OrderLines() {
	}

	public OrderLines(OrderLinesId id, Product product, SaleOrder saleOrder,
			int orderQuantity) {
		this.id = id;
		this.product = product;
		this.saleOrder = saleOrder;
		this.orderQuantity = orderQuantity;
	}

	public OrderLines(OrderLinesId id, Product product, SaleOrder saleOrder,
			int orderQuantity, BigDecimal unitPrice, BigDecimal totalPrice) {
		this.id = id;
		this.product = product;
		this.saleOrder = saleOrder;
		this.orderQuantity = orderQuantity;
		this.unitPrice = unitPrice;
		this.totalPrice = totalPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productCode", column = @Column(name = "Product_Code", nullable = false, length = 30)),
			@AttributeOverride(name = "orderNumber", column = @Column(name = "OrderNumber", nullable = false, length = 30)) })
	public OrderLinesId getId() {
		return this.id;
	}

	public void setId(OrderLinesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Product_Code", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderNumber", nullable = false, insertable = false, updatable = false)
	public SaleOrder getSaleOrder() {
		return this.saleOrder;
	}

	public void setSaleOrder(SaleOrder saleOrder) {
		this.saleOrder = saleOrder;
	}

	@Column(name = "Order_Quantity", nullable = false)
	public int getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(int orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Column(name = "Unit_Price", precision = 10)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "Total_Price", precision = 10)
	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

}
